# Generated by Django 5.1.4 on 2025-01-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_alter_diario_pessoas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diario',
            old_name='creat_at',
            new_name='create_at',
        ),
    ]
